M48
; DRILL file KiCad 10.0.3 date 2026-07-09T00:15:10
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-07-09T00:15:10-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0570
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X8.8322Y-7.1872
X9.3519Y-7.4077
T2
X4.4Y-7.6
X6.0Y-2.7
X10.2Y-2.7
X11.8Y-7.6
M30
