#+title: jazz

some daisy seed effect pedal firmware

run ~nix-shell~ to get dependencies. see [[https://github.com/glittershark/jazz/blob/main/shell.nix][shell.nix]] for a list of dependencies if
you are less of a nix weenie than i am

* building and testing

to build firmware blobs for all effects:

#+begin_src shell-session
$ make
#+end_src

to run tests:

#+begin_src shell-session
$ make test
#+end_src

note: cmake generates ~compile_commands.json~ in the build directory and creates a symlink in the project root for clangd/language server support.

* host audio CLI

for quick iteration without flashing firmware, build the host CLI:

#+begin_src shell-session
$ make console
#+end_src

default behavior is to decode an input mp3, run it through the granular effect, and play it through your computer audio device:

#+begin_src shell-session
$ ./build-test/src/console/jazz-console input.mp3
#+end_src

to save processed audio to a new mp3 while also playing it:

#+begin_src shell-session
$ ./build-test/src/console/jazz-console input.mp3 --output processed.mp3
#+end_src

the CLI depends on ~ffmpeg~ and ~ffplay~ being available in your shell.

* flashing to daisy seed

to flash a particular effect to a daisy seed (in reset mode!):

#+begin_src shell-session
$ make flash DIR=delay
#+end_src

* printing stuff

see [[https://github.com/glittershark/jazz/blob/main/src/console/console.cpp][console]] for how to set up the console. reading from it should be something
like ~screen /dev/ttyACM0 115200~.

* current effects

** delays
- [[https://github.com/glittershark/jazz/blob/main/src/delay/delay.cpp][delay]]: literally just a perfectly clean delay.
- [[https://github.com/glittershark/jazz/blob/main/src/reverse/reverse.cpp][reverse]]: a simple reverse delay.
- [[https://github.com/glittershark/jazz/blob/main/src/granular/granular.cpp][granular]]: weird semi-generative granular delay.
- [[https://github.com/glittershark/jazz/tree/main/src/rachel][rachel]]: heavily modulated multi-delay

** filters
- [[https://github.com/glittershark/jazz/blob/main/src/low_pass_filter/lowpass_filter.cpp][low_pass_filter]]: simple one-pole lowpass filter.
- [[https://github.com/glittershark/jazz/blob/main/src/high_pass_filter/highpass_filter.cpp][high_pass_filter]]: simple one-pole highpass filter.
- [[https://github.com/glittershark/jazz/blob/main/src/cursed_low_pass_filter/cursed_lowpass_filter.cpp][cursed_low_pass_filter]]: cursed lowpass filter using exponentiation and multiplication.
- [[https://github.com/glittershark/jazz/blob/main/src/cursed_high_pass_filter/cursed_highpass_filter.cpp][cursed_high_pass_filter]]: cursed highpass filter using exponentiation and multiplication.

** distortion
- [[https://github.com/glittershark/jazz/blob/main/src/clip/clip.cpp][clip]]: hard clipping distortion.
- [[https://github.com/glittershark/jazz/blob/main/src/anticlip/anticlip.cpp][anticlip]]: adds back the residue from clipping.

** other
- [[https://github.com/glittershark/jazz/blob/main/src/la_sort/la_sort.cpp][la_sort]]: sorting-based effect with weighted tap from sorted buffer.
