TARGET = reverse
CPP_SOURCES = reverse.cpp value.hpp
LIBDAISY_DIR = ../../vendor/libDaisy/
DAISYSP_DIR = ../../vendor/DaisySP/

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
